/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/xterm/xterm-output copy.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Filetree: typeof import('./src/components/filetree/filetree.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    MonacoEditor: typeof import('./src/components/editor/monaco-editor.vue')['default']
    PackagesManager: typeof import('./src/components/menu/packages-manager.vue')['default']
    PackagesManagerTabPyodide: typeof import('./src/components/menu/packages-manager-tab-pyodide.vue')['default']
    PackagesManagerTabPypi: typeof import('./src/components/menu/packages-manager-tab-pypi.vue')['default']
    PackagesTabPyodide: typeof import('./src/components/menu/packages-tab-pyodide.vue')['default']
    PackagesTabPypi: typeof import('./src/components/menu/packages-tab-pypi.vue')['default']
    PyodideStatus: typeof import('./src/components/menu/pyodide-status.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Runbtns: typeof import('./src/components/runbtns.vue')['default']
    Stage: typeof import('./src/components/stage/stage.vue')['default']
    Terminal: typeof import('./src/components/xterm/terminal.vue')['default']
    XtermOutput: typeof import('./src/components/xterm/xterm-output.vue')['default']
  }
}
